import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.PriorityQueue;

/**
 * Created by Neal on 3/26/2016.
 */
public class form2
{
    private JButton btn_DoQuestion_1;
    public JPanel myjpanel;
    private JButton Btn_DoAll;
    private JButton btn_DoQuestion_2a;
    private JTextField fibNum2a;
    private JButton btn_DoQuestion_2b;
    private JTextField fibNum2b;
    private JButton btn_DoQuestion_4;

    public form2()
    {
        $$$setupUI$$$();
        btn_DoQuestion_1.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                kth.Sort(12);
            }
        });

        Btn_DoAll.addActionListener
                (
                        new ActionListener()
                        {
                            /**
                             * Invoked when an action occurs.
                             *
                             * @param e
                             */
                            @Override
                            public void actionPerformed(ActionEvent e)
                            {

                                btn_DoQuestion_1.getActionListeners()[0].actionPerformed(e);
                                btn_DoQuestion_2a.getActionListeners()[0].actionPerformed(e);
                                btn_DoQuestion_2b.getActionListeners()[0].actionPerformed(e);
                                //kth.findHighLow();
                                Excercise4.filterRandomNumb();
                            }
                        });
        btn_DoQuestion_2a.addActionListener(new ActionListener()
        {
            /**
             * Invoked when an action occurs.
             *
             * @param e
             */
            @Override
            public void actionPerformed(ActionEvent e)
            {
                System.out.println();
                System.out.println("<---------- Exercise Question #2a Start ---------->");
                int parameter = Integer.parseInt(fibNum2a.getText());
                Integer[] fibSequence = fibonacci.fibonacci_sequence(parameter);

                for (int i = 1; i < parameter + 1; i++) {
                    System.out.println(i + "#  fibonacci: " + fibSequence[i]);
                }
                System.out.println("<---------- Exercise Question #2a end ---------->");
                System.out.println();
            }
        });
        btn_DoQuestion_2b.addActionListener(new ActionListener()
        {
            /**
             * Invoked when an action occurs.
             *
             * @param e
             */
            @Override
            public void actionPerformed(ActionEvent e)
            {
                System.out.println();
                System.out.println("<---------- Exercise Question #2b Start ---------->");
                int parameter = Integer.parseInt(fibNum2b.getText());
                PriorityQueue<Integer> fibQueue = fibonacci.fibonacciNumber(parameter);
                Integer fib_1 = fibQueue.poll();
                Integer fib_2 = fibQueue.poll();
                System.out.println("Fibnum #" + parameter + " is " + (fib_1 + fib_2) + " (" + fib_1 + "+" + fib_2 + ")");
                System.out.println("<---------- Exercise Question #2b end ---------->");
                System.out.println();
            }
        });
        btn_DoQuestion_4.addActionListener(new ActionListener()
        {
            /**
             * Invoked when an action occurs.
             *
             * @param e
             */
            @Override
            public void actionPerformed(ActionEvent e)
            {
                Excercise4.filterRandomNumb();
            }
        });
    }


    public void center()
    {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.myjpanel.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.myjpanel.getHeight()) / 2);
        this.myjpanel.setLocation(x, y);
    }

    private void createUIComponents()
    {
        // TODO: place custom component creation code here
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        myjpanel = new JPanel();
        myjpanel.setLayout(new GridBagLayout());
        myjpanel.setPreferredSize(new Dimension(400, 400));
        myjpanel.setBorder(BorderFactory.createTitledBorder(null, "My test Title", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION));
        fibNum2a = new JTextField();
        fibNum2a.setText("12");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        myjpanel.add(fibNum2a, gbc);
        btn_DoQuestion_2a = new JButton();
        btn_DoQuestion_2a.setLabel("Do Question #2a");
        btn_DoQuestion_2a.setText("Do Question #2a");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        myjpanel.add(btn_DoQuestion_2a, gbc);
        btn_DoQuestion_1 = new JButton();
        btn_DoQuestion_1.setLabel("Do Question #1");
        btn_DoQuestion_1.setText("Do Question #1");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        myjpanel.add(btn_DoQuestion_1, gbc);
        btn_DoQuestion_2b = new JButton();
        btn_DoQuestion_2b.setLabel("Do Question #2b");
        btn_DoQuestion_2b.setText("Do Question #2b");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        myjpanel.add(btn_DoQuestion_2b, gbc);
        fibNum2b = new JTextField();
        fibNum2b.setText("12");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        myjpanel.add(fibNum2b, gbc);
        btn_DoQuestion_4 = new JButton();
        btn_DoQuestion_4.setActionCommand("");
        btn_DoQuestion_4.setLabel("Do Question #4");
        btn_DoQuestion_4.setText("Do Question #4");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        myjpanel.add(btn_DoQuestion_4, gbc);
        Btn_DoAll = new JButton();
        Btn_DoAll.setActionCommand("");
        Btn_DoAll.setInheritsPopupMenu(true);
        Btn_DoAll.setLabel("Do All Questions");
        Btn_DoAll.setText("Do All Questions");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        myjpanel.add(Btn_DoAll, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return myjpanel;
    }
}
