import javax.swing.*;
import java.awt.*;

/**
 * Created by Neal on 3/28/2016.
 */
public class formTest1
{
    private JButton button1;
    private JPanel panel1;
    private JTextField textField1;
    private JRadioButton radioButton1;
    private JCheckBox checkBox1;
    private JList list1;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        button1 = new JButton();
        button1.setText("Button");
        panel1.add(button1, BorderLayout.CENTER);
        textField1 = new JTextField();
        panel1.add(textField1, BorderLayout.NORTH);
        radioButton1 = new JRadioButton();
        radioButton1.setText("RadioButton");
        panel1.add(radioButton1, BorderLayout.WEST);
        checkBox1 = new JCheckBox();
        checkBox1.setText("CheckBox");
        panel1.add(checkBox1, BorderLayout.SOUTH);
        list1 = new JList();
        panel1.add(list1, BorderLayout.EAST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return panel1;
    }
}
