import javax.swing.*;
import java.awt.*;

/**
 * Created by Neal on 3/28/2016.
 */
public class formtest2
{
    private JButton button1;
    private JPanel panel1;
    private JTextArea textArea1;
    private JRadioButton radioButton1;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        panel1 = new JPanel();
        panel1.setLayout(new CardLayout(0, 0));
        button1 = new JButton();
        button1.setText("Button");
        panel1.add(button1, "Card1");
        textArea1 = new JTextArea();
        panel1.add(textArea1, "Card2");
        radioButton1 = new JRadioButton();
        radioButton1.setText("RadioButton");
        panel1.add(radioButton1, "Card3");
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return panel1;
    }
}
